---
ID: "b9c905a4-1ae3-464b-a1ea-7b32e11c8f95"
Parent: "2d92c37b-30a7-4882-bfd3-f36e8ca463b1"
Template: "2d92c37b-30a7-4882-bfd3-f36e8ca463b1"
Path: /sitecore/templates/Feature/Mulyankan/Base Templates/_link/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231028T085928Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ec230323-0896-4240-93e1-77abeeba547a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231028T085943Z
    - ID: "e5cd72da-959d-43a9-a0bd-aea638831252"
      Hint: title
      Value: $name
