
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

// @ts-ignore Prevent noUnusedLocals from triggering an error, we import all core field types to minimize changing to code generation.
import { Sitecore } from "./_.Sitecore.Override"
// @ts-ignore Prevent noUnusedLocals from triggering an error, we import all core field types to minimize changing to code generation.
import { ComponentRendering, RouteData, Field, ImageField, FileField, LinkField } from '@sitecore-jss/sitecore-jss-nextjs';
// @ts-ignore Prevent noUnusedLocals from triggering an error, we import all core field types to minimize changing to code generation.
import { DefaultComponentProps } from '@/lib/component-props';


export namespace Mulyankan.Fields {
    export type Footer = { 
        fields?: { 
            /**
            * Represents the Title field (bfcf9dc3-27a5-402d-ac1b-72cfc478a0f7).
            */
            Title: LinkField;
 
        }
 }; 
}

export namespace Mulyankan.Fields {
    export type Header = { 
        fields?: { 
            /**
            * Represents the Headline field (54093b7e-1511-49ba-bfca-14d918cd88af).
            */
            Headline: Field<string>;
 
        }
 }; 
}


